### ISSUE TITLE
Missing dependency on CentOS 7

### ISSUE THREAD

**Issue by Kruecke** [bird-house/malleefowl#5]
The malleefowl installation routine fails on a fresh CentOS 7 minimal installation. The package `bzip2` is no longer installed by default which lets `tar` fail at some point.

As far as I understood the setup, this issue might be moved to https://github.com/bird-house/birdhousebuilder.bootstrap. I assume, adding the `bzip2` package over there should be sufficient to fix this problem. I haven't tested if this issue also affects other birdhouse components.

**Comment by cehbrecht** [comment]
i've fixed this (`bzip2`, `tar`, `make`, ...) in the `buildout.sh` for centos builds. 

`buildout.sh` comes from `birdhousebuilder.boostrap` but there is also a copy of it in each birdhouse wps component (malleefowl, emu, ...).

I haven't tried an installation on centos 7 before. But the dockerbuild for centos 6 and 7 seems to work now. There was also an issue with setting up sudo. I've tested it in this way:

    $ cd malleefowl
    $ git pull
    $ vim config/docker.cfg # edit to use centos 7
    $ cat config/docker.cfg
    image-name = centos
    image-version = 7
    $ make dockerbuild
