### ISSUE TITLE
Missing 'wget' on clean Cent OS 7 installation

### ISSUE THREAD

**Issue by Kruecke** [bird-house/malleefowl#7]
![centos](https://cloud.githubusercontent.com/assets/5053254/8256392/1d8ac552-16a7-11e5-934e-dae8ca17f976.png)

Haven't I seen this problem before? Maybe we just added the dependencies to `bootstrap.sh`, but that's not enough as `wget` is used in `Makefile` before.

**Comment by Kruecke** [comment]
This is also true on Ubuntu server 14.04 minimal (virtual) server installation.

**Comment by cehbrecht** [comment]
hopefully i've solved it now. "make sysinstall" triggered also an update of `boostrap.sh` with wget. I've moved this update now to "make selfupdate".

In cases where there is now `make` on the system one needs to call `bootstrap.sh -i` directly first (see Dockerfile).

**Comment by Kruecke** [comment]
Nice, I'll test it.

> In cases where there is no make on the system one needs to call bootstrap.sh -i directly first (see Dockerfile).

Well, I think it should just be clear what is required to be installed in the first place. I'm not sure if it's somewhere in the documentation, but for now I just made sure that `git` and `make` have always been installed on the system before I do anything else.

What I actually wanted to say is that before we are going to handle some crazy cases and mess up the installation scripts, we might just clearly declare what we require. ;-)

**Comment by Kruecke** [comment]
Works now fine. Tested with Ubuntu 14.04 minimal installation which had the same problem as CentOS.
